---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitopsnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitopsnode
  template:
    metadata:
      labels:
        app: gitopsnode
    spec:
      containers:
        - name: app
          image: jainjainjain/gitopsnode:1.0.0
          ports:
            - containerPort: 3000
          imagePullPolicy: Always