---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitopsnode
  annotations:
    flux.weave.works/tag.gitopsnode: glob:*
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitopsnode
  template:
    metadata:
      labels:
        app: gitopsnode
    spec:
      containers:
      - name: app
        image: jainjainjain/gitopsnode:1.0.1
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
